apiVersion: launchpad.mirantis.com/mke/v1.3
kind: mke
metadata:
  name: my-mke-cluster
spec:
  mke:
    version: 3.5.4
    adminUsername: admin
    adminPassword: passw0rd!
    installFlags:
    - --default-node-orchestrator=kubernetes
    - --pod-cidr 10.0.0.0/16
  hosts:
  - role: manager
    ssh:
      user: ubuntu
      address: 20.89.46.192
      keyPath: ./launchpad/examples/terraform/azure/ssh_keys/my-mke-cluster.pem
  - role: manager
    ssh:
      user: ubuntu
      address: 20.89.136.185
      keyPath: ./launchpad/examples/terraform/azure/ssh_keys/my-mke-cluster.pem
  - role: worker
    ssh:
      user: ubuntu
      address: 20.89.46.203
      keyPath: ./launchpad/examples/terraform/azure/ssh_keys/my-mke-cluster.pem
  - role: worker
    ssh:
      user: ubuntu
      address: 20.89.46.235
      keyPath: ./launchpad/examples/terraform/azure/ssh_keys/my-mke-cluster.pem
  - role: worker
    ssh:
      user: ubuntu
      address: 20.89.46.227
      keyPath: ./launchpad/examples/terraform/azure/ssh_keys/my-mke-cluster.pem
